build : 
	g++ gameoflife.cpp \
		imgui/imgui.cpp imgui/imgui_draw.cpp imgui/imgui_widgets.cpp imgui/imgui_tables.cpp \
		imgui/imgui_impl_sdl3.cpp imgui/imgui_impl_sdlrenderer3.cpp	\
		-I C:/libraries/SDL3-3.2.8/x86_64-w64-mingw32/include \
	    -L C:/libraries/SDL3-3.2.8/x86_64-w64-mingw32/lib -lSDL3 \
		-o gameoflife
